name: Deploy Lambda Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Deploy Lambda function
      uses: aws-actions/aws-lambda-deploy@v1.0.0
      with:
        function-name: cost-notify-lambda
        zip-file: cost-notfiy.py
        handler: cost-notfiy.lambda_handler
        runtime: python3.9
        role: ${{ secrets.LAMBDA_EXECUTION_ROLE_ARN }}
        environment-variables: |
          LINEtoken=${{ secrets.LINE_TOKEN }}
          groupID=${{ secrets.GROUP_ID }}